### ISSUE TITLE
Investigate supporting 'short' canary lifetimes

### ISSUE THREAD

**Issue by duftler** [spinnaker/kayenta#283]
We currently only support specifying overall duration via a non-fractional number of hours.

**Comment by skandragon** [comment]
I don't think this is an issue in kayenta, which takes a start and end time for metrics.  There is a minimum number of data points we'd like (50 ideally) and accuracy changes as that gets smaller.

**Comment by duftler** [comment]
It's an issue in using kayenta, but doesn't live within the kayenta codebase.

This attribute (https://github.com/spinnaker/orca/blob/master/orca-kayenta/src/main/kotlin/com/netflix/spinnaker/orca/kayenta/model/KayentaCanaryContext.kt#L30) expects an int representing the number of hours in the overall canary lifetime. We'd need to change that to a duration or (this is probably a shorter path too) a non-int.

**Comment by sbwsg** [comment]
If possible: Look to surface the minimum number of data points either alongside results or, if the provider supports step size, alongside the config UI.

**Comment by sbwsg** [comment]
What are "data points" in this context?  Is it the # of canary runs or something completely different?

**Comment by dotdotdotpaul** [comment]
FWIW, DataDog always returns approximately the same number of datapoints for any given time series.

**Comment by duftler** [comment]
So do you think it makes sense to just not provide that guidance if DataDog is in use? Or is there some alternative guidance that would make sense instead?

**Comment by dotdotdotpaul** [comment]
If we can set guidance depending on the metric source in use, it would definitely make sense to leave off the "guidelines" for Datadog, since the user won't have any control over how many datapoints are returned anyway.  It's not critical to be so precise, I don't think, if the guidelines are generic and say something like "refer to your metrics provider for details" or something like that.  I don't know if other metric sources might also need different guidelines for whatever reason.

**Comment by duftler** [comment]
Thanks. It's mainly that the judge expects a certain number and we want to provide that information to the user, even if they can't necessarily do anything about it (if nothing else, should let them know to have less confidence in the judgment).

**Comment by duftler** [comment]
For DataDog, wouldn't increasing the amount of time that the newly-provisioned resources are running (and publishing metrics) allow for a greater number of data points to be returned by the subsequent canary run?

**Comment by dotdotdotpaul** [comment]
Not sure it matters, since Kayenta will be judging based on the same interval; -- or if it matters, it'll be specific to the metric being used.  Datadog can (and will) return sparse data, so if the new server isn't really running until partway through the first judgment interval, it'll be obvious in the results (the canary will show null/zero points early in the sequence).

Over time, Datadog just returns larger timeslices as buckets.  So if you ask for data for a 10-minute period, you might get 15 second or 30 second buckets; if you ask for an hour, you'll get 5-minute buckets.  So the number of points returned is always "about the same", the granularity is just different.
