### ISSUE TITLE
Copying canary start/end time format differs

### ISSUE THREAD

**Issue by jtk54** [spinnaker/kayenta#590]
The copied value is different than the rendered value when copying canary start and end times from the UI:

![image](https://user-images.githubusercontent.com/5456773/61389165-6bd95500-a886-11e9-86c1-fd304ef97c0e.png)

The copied value is indeed formatted correctly, but I think the UI is a bit confusing currently.

**Comment by fieldju** [comment]
Are you saying that it is confusing because the displayed date timestamp is your local time while the copied date timestamp is an ISO 8061 timestamp?

**Comment by jtk54** [comment]
Yes.

**Comment by fieldju** [comment]
OK, well this project is the backend for that user interface and all of it's timestamps are in ISO 8061 / epochmillis format.

Your issue is really with the [Deck Kayenta](https://github.com/spinnaker/deck-kayenta) project, please open this issue [here instead](https://github.com/spinnaker/deck-kayenta/issues).
