### ISSUE TITLE
upgrade openjdk to get rid of known vulnerabilities

### ISSUE THREAD

**Issue by segaura** [spinnaker/kayenta#640]
Dockerfile uses openjdk:8-alpine, any openjdk version 8 is no longer supported and contains many known serious vulnerabilities.

Are you considering upgrading to the latest openjdk, now 13, so it is supported and fixed?

NOTE: since openjdk 9 the alpine version is no longer built, the thinnest alternative is the "slim" versin

**Comment by fieldju** [comment]
I believe there is a ticket to consider moving things to OpenJdK 11, the current LTS.
No one in the enterprise world is looking at non-lts releases (aka 10, 12, 13).

@duftler I would vote to update those docker files to some image that uses Adopt Open JDK 8's JDK/JRE which has Java 8 support until the end of Sept 2023.

https://adoptopenjdk.net/support.html

This could provide a good stop gap until:
https://github.com/spinnaker/spinnaker/issues/4317

**Comment by fieldju** [comment]
CC: @nisanharamati

**Comment by fieldju** [comment]
https://github.com/spinnaker/community/pull/62

**Comment by duftler** [comment]
Switching from alpine 8 to openjdk 8 seems reasonable to me.

Worth pointing out that those changes wouldn't be reflected until the next release (early January), and the linked rfc with the plan to move everything to 11 proposes having _all_ components on 11 by early March. Is it worth the potential risk to avoid just waiting until then?

**Comment by nisanharamati** [comment]
Both approaches sound fine to me. It does sound from @duftler 's comment that it's worth checking in and possibly coordinating with the Java 11 migration effort.

Has anyone taken a look at how much work is involved in one vs. the other (Adopt OpenJDK8 vs. OpenJDK 11)?

**Comment by plumpy** [comment]
Hey, I was looking into the status of OpenJDK 8 as part of [the aforementioned Java 11 upgrade RFC](https://github.com/spinnaker/community/pull/62). It's pretty confusing, but it's definitely not true that "any openjdk version 8 is no longer supported". Oracle no longer publishes builds of OpenJDK 8, so I think that's where the confusion comes from, but the OpenJDK project still merges security fixes and tags releases, you just have to get the builds from somewhere else, usually your OS vendor.

The Dockerfiles specify an _operating system_, not a JRE. For `Dockerfile.slim`, we're using the Alpine distro via the `openjdk:8-jre-alpine` container. Unfortunately, that container hasn't been updated in 7 months, so it's using a version of OpenJDK 8 from April (8u212). Newer versions of Alpine have more modern JREs, but the real issue here is the staleness of that image. The JDK is just one of many components that are likely out of date.

The `Dockerfile.ubuntu` container, on the other hand, uses Ubuntu bionic, which bundles OpenJDK 8u222 from August, so it's still pretty current. There was an 8u232 in October that they will presumably update to soon and we'll get that automatically in any container built afterward.

I think what we want to do (across all of Spinnaker) is update our `Dockerfile.slim` files to do something like this:

```
FROM alpine:3.10
RUN apk add openjdk-8-jre-headless
```

**Comment by plumpy** [comment]
Closing this in favor of the more general Spinnaker issue...
